markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: 江南伪文艺范                                               # 博客名称
    description: 理工实验狗的流水博客                                        # 博客描述
    title: 江南伪文艺范                                              # 网页标题
    url: http://blog.liuyang.cf                                                # 博客地址
    duoshuo: younglau                                            # 多说ID
    tongji: 6379771                                             # 百度统计ID
    qiniu: https://portal.qiniu.com/bucket/younglau/index                                              # 七牛云地址
author:
    name: YoungLau                                               # 作者名称
    email:  i@younglau.info                                              # 邮箱地址
    weibo: http://weibo.com/3177171815                                              # 微博地址
    github: https://github.com/flyingyouth/Jekyll-Light                                             # GitHub地址
    logo: https://github.com/flyingyouth/Jekyll-Light/blob/gh-pages/photos/logo.png                                              # logo地址
    douban:
        name: 梦飞扬，正青春                                           # 豆瓣地址名称
        key: 0bd72f3e0c94a02b23858dba25bde081                                            # 豆瓣API Key
